// JVLinkToSQLite は、JRA-VAN データラボが提供する競馬データを SQLite データベースに変換するツールです。
// 
// Copyright (C) 2023 Akira Sugiura
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// 
// Additional permission under GNU GPL version 3 section 7
// 
// If you modify this Program, or any covered work, by linking or combining it with 
// ObscUra (or a modified version of that library), containing parts covered 
// by the terms of ObscUra's license, the licensors of this Program grant you 
// additional permission to convey the resulting work.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text.RegularExpressions;
using static Urasandesu.JVLinkToSQLite.JVLinkWrappers.JVCategorySpec;
using static Urasandesu.JVLinkToSQLite.JVLinkWrappers.JVRecordSpec;

namespace Urasandesu.JVLinkToSQLite.JVLinkWrappers
{
    [DebuggerDisplay("{" + nameof(Value) + "}, " +
                     nameof(RecordSpec) + "={" + nameof(RecordSpec) + "}, " +
                     nameof(CategorySpec) + "={" + nameof(CategorySpec) + "}, " +
                     nameof(SaveSpec) + "={" + nameof(SaveSpec) + "}, " +
                     nameof(FileNameRegex) + "={" + nameof(FileNameRegex) + "}, " +
                     nameof(ProvidedDuration) + "={" + nameof(ProvidedDuration) + "}")]
    public class JVDataFileSpec : IEquatable<JVDataFileSpec>
    {
        public static readonly JVDataFileSpec TOKU_TK_T_W = new JVDataFileSpec() { Value = nameof(TOKU_TK_T_W), RecordSpec = TK, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"TKTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TOKU_TK_H_W = new JVDataFileSpec() { Value = nameof(TOKU_TK_H_W), RecordSpec = TK, CategorySpec = H, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"TKHW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TOKU_TK_M_W = new JVDataFileSpec() { Value = nameof(TOKU_TK_M_W), RecordSpec = TK, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"TKMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec TCOV_UM_T_W = new JVDataFileSpec() { Value = nameof(TCOV_UM_T_W), RecordSpec = UM, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_CH_T_W = new JVDataFileSpec() { Value = nameof(TCOV_CH_T_W), RecordSpec = CH, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_BR_T_W = new JVDataFileSpec() { Value = nameof(TCOV_BR_T_W), RecordSpec = BR, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_BN_T_W = new JVDataFileSpec() { Value = nameof(TCOV_BN_T_W), RecordSpec = BN, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_RC_T_W = new JVDataFileSpec() { Value = nameof(TCOV_RC_T_W), RecordSpec = RC, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_RA_U_W = new JVDataFileSpec() { Value = nameof(TCOV_RA_U_W), RecordSpec = RA, CategorySpec = U, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAUW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCOV_SE_U_W = new JVDataFileSpec() { Value = nameof(TCOV_SE_U_W), RecordSpec = SE, CategorySpec = U, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEUW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_UM_T_W = new JVDataFileSpec() { Value = nameof(TCVN_UM_T_W), RecordSpec = UM, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_CH_T_W = new JVDataFileSpec() { Value = nameof(TCVN_CH_T_W), RecordSpec = CH, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_BR_T_W = new JVDataFileSpec() { Value = nameof(TCVN_BR_T_W), RecordSpec = BR, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_BN_T_W = new JVDataFileSpec() { Value = nameof(TCVN_BN_T_W), RecordSpec = BN, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_RC_T_W = new JVDataFileSpec() { Value = nameof(TCVN_RC_T_W), RecordSpec = RC, CategorySpec = T, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCTW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_RA_U_W = new JVDataFileSpec() { Value = nameof(TCVN_RA_U_W), RecordSpec = RA, CategorySpec = U, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAUW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec TCVN_SE_U_W = new JVDataFileSpec() { Value = nameof(TCVN_SE_U_W), RecordSpec = SE, CategorySpec = U, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEUW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RACE_RA_G_W = new JVDataFileSpec() { Value = nameof(RACE_RA_G_W), RecordSpec = RA, CategorySpec = G, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAGW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(1) };
        public static readonly JVDataFileSpec RACE_RA_P_W = new JVDataFileSpec() { Value = nameof(RACE_RA_P_W), RecordSpec = RA, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(1) };
        public static readonly JVDataFileSpec RACE_RA_D_W = new JVDataFileSpec() { Value = nameof(RACE_RA_D_W), RecordSpec = RA, CategorySpec = D, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RADW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(3) };
        public static readonly JVDataFileSpec RACE_RA_B_W = new JVDataFileSpec() { Value = nameof(RACE_RA_B_W), RecordSpec = RA, CategorySpec = B, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RABW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(3) };
        public static readonly JVDataFileSpec RACE_RA_S_W = new JVDataFileSpec() { Value = nameof(RACE_RA_S_W), RecordSpec = RA, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RASW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_RA_M_W = new JVDataFileSpec() { Value = nameof(RACE_RA_M_W), RecordSpec = RA, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_SE_G_W = new JVDataFileSpec() { Value = nameof(RACE_SE_G_W), RecordSpec = SE, CategorySpec = G, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEGW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(1) };
        public static readonly JVDataFileSpec RACE_SE_P_W = new JVDataFileSpec() { Value = nameof(RACE_SE_P_W), RecordSpec = SE, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(1) };
        public static readonly JVDataFileSpec RACE_SE_D_W = new JVDataFileSpec() { Value = nameof(RACE_SE_D_W), RecordSpec = SE, CategorySpec = D, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEDW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(3) };
        public static readonly JVDataFileSpec RACE_SE_B_W = new JVDataFileSpec() { Value = nameof(RACE_SE_B_W), RecordSpec = SE, CategorySpec = B, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEBW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(3) };
        public static readonly JVDataFileSpec RACE_SE_S_W = new JVDataFileSpec() { Value = nameof(RACE_SE_S_W), RecordSpec = SE, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SESW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_SE_M_W = new JVDataFileSpec() { Value = nameof(RACE_SE_M_W), RecordSpec = SE, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_HR_S_W = new JVDataFileSpec() { Value = nameof(RACE_HR_S_W), RecordSpec = HR, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HRSW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_HR_M_W = new JVDataFileSpec() { Value = nameof(RACE_HR_M_W), RecordSpec = HR, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HRMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_H1_S_W = new JVDataFileSpec() { Value = nameof(RACE_H1_S_W), RecordSpec = H1, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"H1SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_H1_M_W = new JVDataFileSpec() { Value = nameof(RACE_H1_M_W), RecordSpec = H1, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"H1SMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_H6_S_W = new JVDataFileSpec() { Value = nameof(RACE_H6_S_W), RecordSpec = H6, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"H6SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_H6_M_W = new JVDataFileSpec() { Value = nameof(RACE_H6_M_W), RecordSpec = H6, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"H6SMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O1_S_W = new JVDataFileSpec() { Value = nameof(RACE_O1_S_W), RecordSpec = O1, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O1SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O1_M_W = new JVDataFileSpec() { Value = nameof(RACE_O1_M_W), RecordSpec = O1, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O1MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O2_S_W = new JVDataFileSpec() { Value = nameof(RACE_O2_S_W), RecordSpec = O2, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O2SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O2_M_W = new JVDataFileSpec() { Value = nameof(RACE_O2_M_W), RecordSpec = O2, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O2MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O3_S_W = new JVDataFileSpec() { Value = nameof(RACE_O3_S_W), RecordSpec = O3, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O3SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O3_M_W = new JVDataFileSpec() { Value = nameof(RACE_O3_M_W), RecordSpec = O3, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O3MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O4_S_W = new JVDataFileSpec() { Value = nameof(RACE_O4_S_W), RecordSpec = O4, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O4SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O4_M_W = new JVDataFileSpec() { Value = nameof(RACE_O4_M_W), RecordSpec = O4, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O4MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O5_S_W = new JVDataFileSpec() { Value = nameof(RACE_O5_S_W), RecordSpec = O5, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O5SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O5_M_W = new JVDataFileSpec() { Value = nameof(RACE_O5_M_W), RecordSpec = O5, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O5MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O6_S_W = new JVDataFileSpec() { Value = nameof(RACE_O6_S_W), RecordSpec = O6, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O6SW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O6_M_W = new JVDataFileSpec() { Value = nameof(RACE_O6_M_W), RecordSpec = O6, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"O6MW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_WF_S_W = new JVDataFileSpec() { Value = nameof(RACE_WF_S_W), RecordSpec = WF, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"WFSW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_WF_M_W = new JVDataFileSpec() { Value = nameof(RACE_WF_M_W), RecordSpec = WF, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"WFMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_JG_D_W = new JVDataFileSpec() { Value = nameof(RACE_JG_D_W), RecordSpec = JG, CategorySpec = D, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"JGDW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(4) };
        public static readonly JVDataFileSpec RACE_JG_M_W = new JVDataFileSpec() { Value = nameof(RACE_JG_M_W), RecordSpec = JG, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"JGMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RCOV_UM_P_W = new JVDataFileSpec() { Value = nameof(RCOV_UM_P_W), RecordSpec = UM, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_KS_P_W = new JVDataFileSpec() { Value = nameof(RCOV_KS_P_W), RecordSpec = KS, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_CH_P_W = new JVDataFileSpec() { Value = nameof(RCOV_CH_P_W), RecordSpec = CH, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_BR_P_W = new JVDataFileSpec() { Value = nameof(RCOV_BR_P_W), RecordSpec = BR, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_BN_P_W = new JVDataFileSpec() { Value = nameof(RCOV_BN_P_W), RecordSpec = BN, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_RC_P_W = new JVDataFileSpec() { Value = nameof(RCOV_RC_P_W), RecordSpec = RC, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_RA_Q_W = new JVDataFileSpec() { Value = nameof(RCOV_RA_Q_W), RecordSpec = RA, CategorySpec = Q, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAQW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCOV_SE_Q_W = new JVDataFileSpec() { Value = nameof(RCOV_SE_Q_W), RecordSpec = SE, CategorySpec = Q, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEQW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_UM_P_W = new JVDataFileSpec() { Value = nameof(RCVN_UM_P_W), RecordSpec = UM, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_KS_P_W = new JVDataFileSpec() { Value = nameof(RCVN_KS_P_W), RecordSpec = KS, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_CH_P_W = new JVDataFileSpec() { Value = nameof(RCVN_CH_P_W), RecordSpec = CH, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_BR_P_W = new JVDataFileSpec() { Value = nameof(RCVN_BR_P_W), RecordSpec = BR, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_BN_P_W = new JVDataFileSpec() { Value = nameof(RCVN_BN_P_W), RecordSpec = BN, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_RC_P_W = new JVDataFileSpec() { Value = nameof(RCVN_RC_P_W), RecordSpec = RC, CategorySpec = P, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCPW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_RA_Q_W = new JVDataFileSpec() { Value = nameof(RCVN_RA_Q_W), RecordSpec = RA, CategorySpec = Q, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAQW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec RCVN_SE_Q_W = new JVDataFileSpec() { Value = nameof(RCVN_SE_Q_W), RecordSpec = SE, CategorySpec = Q, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEQW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(7) };
        public static readonly JVDataFileSpec DIFF_UM_F_W = new JVDataFileSpec() { Value = nameof(DIFF_UM_F_W), RecordSpec = UM, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_UM_O_W = new JVDataFileSpec() { Value = nameof(DIFF_UM_O_W), RecordSpec = UM, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_KS_F_W = new JVDataFileSpec() { Value = nameof(DIFF_KS_F_W), RecordSpec = KS, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_KS_O_W = new JVDataFileSpec() { Value = nameof(DIFF_KS_O_W), RecordSpec = KS, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_CH_F_W = new JVDataFileSpec() { Value = nameof(DIFF_CH_F_W), RecordSpec = CH, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_CH_O_W = new JVDataFileSpec() { Value = nameof(DIFF_CH_O_W), RecordSpec = CH, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_BR_F_W = new JVDataFileSpec() { Value = nameof(DIFF_BR_F_W), RecordSpec = BR, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_BR_O_W = new JVDataFileSpec() { Value = nameof(DIFF_BR_O_W), RecordSpec = BR, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BROW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_BN_F_W = new JVDataFileSpec() { Value = nameof(DIFF_BN_F_W), RecordSpec = BN, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_BN_O_W = new JVDataFileSpec() { Value = nameof(DIFF_BN_O_W), RecordSpec = BN, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_RC_F_W = new JVDataFileSpec() { Value = nameof(DIFF_RC_F_W), RecordSpec = RC, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_RC_O_W = new JVDataFileSpec() { Value = nameof(DIFF_RC_O_W), RecordSpec = RC, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_RA_L_W = new JVDataFileSpec() { Value = nameof(DIFF_RA_L_W), RecordSpec = RA, CategorySpec = L, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RALW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_RA_K_W = new JVDataFileSpec() { Value = nameof(DIFF_RA_K_W), RecordSpec = RA, CategorySpec = K, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAKW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_RA_O_W = new JVDataFileSpec() { Value = nameof(DIFF_RA_O_W), RecordSpec = RA, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_SE_L_W = new JVDataFileSpec() { Value = nameof(DIFF_SE_L_W), RecordSpec = SE, CategorySpec = L, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SELW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_SE_K_W = new JVDataFileSpec() { Value = nameof(DIFF_SE_K_W), RecordSpec = SE, CategorySpec = K, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEKW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_SE_O_W = new JVDataFileSpec() { Value = nameof(DIFF_SE_O_W), RecordSpec = SE, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_UM_F_W = new JVDataFileSpec() { Value = nameof(DIFN_UM_F_W), RecordSpec = UM, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_UM_O_W = new JVDataFileSpec() { Value = nameof(DIFN_UM_O_W), RecordSpec = UM, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"UMOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_KS_F_W = new JVDataFileSpec() { Value = nameof(DIFN_KS_F_W), RecordSpec = KS, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_KS_O_W = new JVDataFileSpec() { Value = nameof(DIFN_KS_O_W), RecordSpec = KS, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"KSOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_CH_F_W = new JVDataFileSpec() { Value = nameof(DIFN_CH_F_W), RecordSpec = CH, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_CH_O_W = new JVDataFileSpec() { Value = nameof(DIFN_CH_O_W), RecordSpec = CH, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CHOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_BR_F_W = new JVDataFileSpec() { Value = nameof(DIFN_BR_F_W), RecordSpec = BR, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BRFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_BR_O_W = new JVDataFileSpec() { Value = nameof(DIFN_BR_O_W), RecordSpec = BR, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BROW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_BN_F_W = new JVDataFileSpec() { Value = nameof(DIFN_BN_F_W), RecordSpec = BN, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_BN_O_W = new JVDataFileSpec() { Value = nameof(DIFN_BN_O_W), RecordSpec = BN, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BNOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_RC_F_W = new JVDataFileSpec() { Value = nameof(DIFN_RC_F_W), RecordSpec = RC, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_RC_O_W = new JVDataFileSpec() { Value = nameof(DIFN_RC_O_W), RecordSpec = RC, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RCOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_RA_L_W = new JVDataFileSpec() { Value = nameof(DIFN_RA_L_W), RecordSpec = RA, CategorySpec = L, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RALW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_RA_K_W = new JVDataFileSpec() { Value = nameof(DIFN_RA_K_W), RecordSpec = RA, CategorySpec = K, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAKW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_RA_O_W = new JVDataFileSpec() { Value = nameof(DIFN_RA_O_W), RecordSpec = RA, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"RAOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFN_SE_L_W = new JVDataFileSpec() { Value = nameof(DIFN_SE_L_W), RecordSpec = SE, CategorySpec = L, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SELW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_SE_K_W = new JVDataFileSpec() { Value = nameof(DIFN_SE_K_W), RecordSpec = SE, CategorySpec = K, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEKW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_SE_O_W = new JVDataFileSpec() { Value = nameof(DIFN_SE_O_W), RecordSpec = SE, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SEOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLOD_HN_F_W = new JVDataFileSpec() { Value = nameof(BLOD_HN_F_W), RecordSpec = HN, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HNFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLOD_HN_M_W = new JVDataFileSpec() { Value = nameof(BLOD_HN_M_W), RecordSpec = HN, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HNMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLOD_SK_F_W = new JVDataFileSpec() { Value = nameof(BLOD_SK_F_W), RecordSpec = SK, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SKFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLOD_SK_M_W = new JVDataFileSpec() { Value = nameof(BLOD_SK_M_W), RecordSpec = SK, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SKMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLOD_BT_F_W = new JVDataFileSpec() { Value = nameof(BLOD_BT_F_W), RecordSpec = BT, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BTFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLDN_HN_F_W = new JVDataFileSpec() { Value = nameof(BLDN_HN_F_W), RecordSpec = HN, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HNFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLDN_HN_M_W = new JVDataFileSpec() { Value = nameof(BLDN_HN_M_W), RecordSpec = HN, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HNMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLDN_SK_F_W = new JVDataFileSpec() { Value = nameof(BLDN_SK_F_W), RecordSpec = SK, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SKFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLDN_SK_M_W = new JVDataFileSpec() { Value = nameof(BLDN_SK_M_W), RecordSpec = SK, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"SKMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLDN_BT_F_W = new JVDataFileSpec() { Value = nameof(BLDN_BT_F_W), RecordSpec = BT, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"BTFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec SLOP_HC_E_W = new JVDataFileSpec() { Value = nameof(SLOP_HC_E_W), RecordSpec = HC, CategorySpec = E, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HCEW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SLOP_HC_W_W = new JVDataFileSpec() { Value = nameof(SLOP_HC_W_W), RecordSpec = HC, CategorySpec = W, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HCWW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SLOP_HC_M_W = new JVDataFileSpec() { Value = nameof(SLOP_HC_M_W), RecordSpec = HC, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HCMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec YSCH_YS_N_W = new JVDataFileSpec() { Value = nameof(YSCH_YS_N_W), RecordSpec = YS, CategorySpec = N, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"YSNW(?<datekey>[0-9]{4}9999)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec YSCH_YS_M_W = new JVDataFileSpec() { Value = nameof(YSCH_YS_M_W), RecordSpec = YS, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"YSMW(?<datekey>[0-9]{4}9999)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec HOSE_HS_F_W = new JVDataFileSpec() { Value = nameof(HOSE_HS_F_W), RecordSpec = HS, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HSFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec HOSN_HS_F_W = new JVDataFileSpec() { Value = nameof(HOSN_HS_F_W), RecordSpec = HS, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HSFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec SNAP_CK_F_W = new JVDataFileSpec() { Value = nameof(SNAP_CK_F_W), RecordSpec = CK, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNAP_CK_C_W = new JVDataFileSpec() { Value = nameof(SNAP_CK_C_W), RecordSpec = CK, CategorySpec = C, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKCW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNAP_CK_M_W = new JVDataFileSpec() { Value = nameof(SNAP_CK_M_W), RecordSpec = CK, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec SNPN_CK_F_W = new JVDataFileSpec() { Value = nameof(SNPN_CK_F_W), RecordSpec = CK, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNPN_CK_C_W = new JVDataFileSpec() { Value = nameof(SNPN_CK_C_W), RecordSpec = CK, CategorySpec = C, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKCW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNPN_CK_M_W = new JVDataFileSpec() { Value = nameof(SNPN_CK_M_W), RecordSpec = CK, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CKMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec HOYU_HY_F_W = new JVDataFileSpec() { Value = nameof(HOYU_HY_F_W), RecordSpec = HY, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HYFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec HOYU_HY_O_W = new JVDataFileSpec() { Value = nameof(HOYU_HY_O_W), RecordSpec = HY, CategorySpec = O, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"HYOW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec COMM_CS_F_W = new JVDataFileSpec() { Value = nameof(COMM_CS_F_W), RecordSpec = CS, CategorySpec = F, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"CSFW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec MING_DM_S_W = new JVDataFileSpec() { Value = nameof(MING_DM_S_W), RecordSpec = DM, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"DMSW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec MING_TM_S_W = new JVDataFileSpec() { Value = nameof(MING_TM_S_W), RecordSpec = TM, CategorySpec = S, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"TMSW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec WOOD_WC_E_W = new JVDataFileSpec() { Value = nameof(WOOD_WC_E_W), RecordSpec = WC, CategorySpec = E, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"WCEW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec WOOD_WC_W_W = new JVDataFileSpec() { Value = nameof(WOOD_WC_W_W), RecordSpec = WC, CategorySpec = W, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"WCWW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec WOOD_WC_M_W = new JVDataFileSpec() { Value = nameof(WOOD_WC_M_W), RecordSpec = WC, CategorySpec = M, SaveSpec = JVSaveSpec.W, FileNameRegex = new Regex(@"WCMW(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_RA_V_M = new JVDataFileSpec() { Value = nameof(RACE_RA_V_M), RecordSpec = RA, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"RAVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_RA_M_M = new JVDataFileSpec() { Value = nameof(RACE_RA_M_M), RecordSpec = RA, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"RAMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_SE_V_M = new JVDataFileSpec() { Value = nameof(RACE_SE_V_M), RecordSpec = SE, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SEVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_SE_M_M = new JVDataFileSpec() { Value = nameof(RACE_SE_M_M), RecordSpec = SE, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SEMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_HR_V_M = new JVDataFileSpec() { Value = nameof(RACE_HR_V_M), RecordSpec = HR, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HRVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_HR_M_M = new JVDataFileSpec() { Value = nameof(RACE_HR_M_M), RecordSpec = HR, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HRMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_H1_V_M = new JVDataFileSpec() { Value = nameof(RACE_H1_V_M), RecordSpec = H1, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"H1VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_H1_M_M = new JVDataFileSpec() { Value = nameof(RACE_H1_M_M), RecordSpec = H1, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"H1MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_H6_V_M = new JVDataFileSpec() { Value = nameof(RACE_H6_V_M), RecordSpec = H6, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"H6VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_H6_M_M = new JVDataFileSpec() { Value = nameof(RACE_H6_M_M), RecordSpec = H6, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"H6MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O1_V_M = new JVDataFileSpec() { Value = nameof(RACE_O1_V_M), RecordSpec = O1, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O1VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O1_M_M = new JVDataFileSpec() { Value = nameof(RACE_O1_M_M), RecordSpec = O1, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O1MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O2_V_M = new JVDataFileSpec() { Value = nameof(RACE_O2_V_M), RecordSpec = O2, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O2VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O2_M_M = new JVDataFileSpec() { Value = nameof(RACE_O2_M_M), RecordSpec = O2, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O2MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O3_V_M = new JVDataFileSpec() { Value = nameof(RACE_O3_V_M), RecordSpec = O3, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O3VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O3_M_M = new JVDataFileSpec() { Value = nameof(RACE_O3_M_M), RecordSpec = O3, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O3MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O4_V_M = new JVDataFileSpec() { Value = nameof(RACE_O4_V_M), RecordSpec = O4, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O4VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O4_M_M = new JVDataFileSpec() { Value = nameof(RACE_O4_M_M), RecordSpec = O4, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O4MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O5_V_M = new JVDataFileSpec() { Value = nameof(RACE_O5_V_M), RecordSpec = O5, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O5VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O5_M_M = new JVDataFileSpec() { Value = nameof(RACE_O5_M_M), RecordSpec = O5, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O5MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_O6_V_M = new JVDataFileSpec() { Value = nameof(RACE_O6_V_M), RecordSpec = O6, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O6VM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_O6_M_M = new JVDataFileSpec() { Value = nameof(RACE_O6_M_M), RecordSpec = O6, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"O6MM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_WF_V_M = new JVDataFileSpec() { Value = nameof(RACE_WF_V_M), RecordSpec = WF, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"WFVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_WF_M_M = new JVDataFileSpec() { Value = nameof(RACE_WF_M_M), RecordSpec = WF, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"WFMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec RACE_JG_V_M = new JVDataFileSpec() { Value = nameof(RACE_JG_V_M), RecordSpec = JG, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"JGVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec RACE_JG_M_M = new JVDataFileSpec() { Value = nameof(RACE_JG_M_M), RecordSpec = JG, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"JGMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec DIFF_UM_X_M = new JVDataFileSpec() { Value = nameof(DIFF_UM_X_M), RecordSpec = UM, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"UMXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_KS_X_M = new JVDataFileSpec() { Value = nameof(DIFF_KS_X_M), RecordSpec = KS, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"KSXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_CH_X_M = new JVDataFileSpec() { Value = nameof(DIFF_CH_X_M), RecordSpec = CH, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CHXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_BR_X_M = new JVDataFileSpec() { Value = nameof(DIFF_BR_X_M), RecordSpec = BR, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BRXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_BN_X_M = new JVDataFileSpec() { Value = nameof(DIFF_BN_X_M), RecordSpec = BN, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BNXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFF_RC_X_M = new JVDataFileSpec() { Value = nameof(DIFF_RC_X_M), RecordSpec = RC, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"RCXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_UM_X_M = new JVDataFileSpec() { Value = nameof(DIFN_UM_X_M), RecordSpec = UM, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"UMXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_KS_X_M = new JVDataFileSpec() { Value = nameof(DIFN_KS_X_M), RecordSpec = KS, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"KSXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_CH_X_M = new JVDataFileSpec() { Value = nameof(DIFN_CH_X_M), RecordSpec = CH, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CHXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_BR_X_M = new JVDataFileSpec() { Value = nameof(DIFN_BR_X_M), RecordSpec = BR, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BRXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_BN_X_M = new JVDataFileSpec() { Value = nameof(DIFN_BN_X_M), RecordSpec = BN, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BNXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec DIFN_RC_X_M = new JVDataFileSpec() { Value = nameof(DIFN_RC_X_M), RecordSpec = RC, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"RCXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLOD_HN_V_M = new JVDataFileSpec() { Value = nameof(BLOD_HN_V_M), RecordSpec = HN, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HNVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLOD_HN_M_M = new JVDataFileSpec() { Value = nameof(BLOD_HN_M_M), RecordSpec = HN, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HNMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLOD_SK_V_M = new JVDataFileSpec() { Value = nameof(BLOD_SK_V_M), RecordSpec = SK, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SKVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLOD_SK_M_M = new JVDataFileSpec() { Value = nameof(BLOD_SK_M_M), RecordSpec = SK, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SKMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLOD_BT_X_M = new JVDataFileSpec() { Value = nameof(BLOD_BT_X_M), RecordSpec = BT, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BTXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLDN_HN_V_M = new JVDataFileSpec() { Value = nameof(BLDN_HN_V_M), RecordSpec = HN, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HNVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLDN_HN_M_M = new JVDataFileSpec() { Value = nameof(BLDN_HN_M_M), RecordSpec = HN, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HNMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLDN_SK_V_M = new JVDataFileSpec() { Value = nameof(BLDN_SK_V_M), RecordSpec = SK, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SKVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec BLDN_SK_M_M = new JVDataFileSpec() { Value = nameof(BLDN_SK_M_M), RecordSpec = SK, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"SKMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec BLDN_BT_X_M = new JVDataFileSpec() { Value = nameof(BLDN_BT_X_M), RecordSpec = BT, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"BTXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SLOP_HC_V_M = new JVDataFileSpec() { Value = nameof(SLOP_HC_V_M), RecordSpec = HC, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HCVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SLOP_HC_M_M = new JVDataFileSpec() { Value = nameof(SLOP_HC_M_M), RecordSpec = HC, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HCMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec YSCH_YS_Y_M = new JVDataFileSpec() { Value = nameof(YSCH_YS_Y_M), RecordSpec = YS, CategorySpec = Y, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"YSYM(?<datekey>[0-9]{4}9999)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec YSCH_YS_M_M = new JVDataFileSpec() { Value = nameof(YSCH_YS_M_M), RecordSpec = YS, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"YSMM(?<datekey>[0-9]{4}9999)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec SNAP_CK_V_M = new JVDataFileSpec() { Value = nameof(SNAP_CK_V_M), RecordSpec = CK, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CKVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNAP_CK_M_M = new JVDataFileSpec() { Value = nameof(SNAP_CK_M_M), RecordSpec = CK, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CKMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec SNPN_CK_V_M = new JVDataFileSpec() { Value = nameof(SNPN_CK_V_M), RecordSpec = CK, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CKVM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec SNPN_CK_M_M = new JVDataFileSpec() { Value = nameof(SNPN_CK_M_M), RecordSpec = CK, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CKMM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };
        public static readonly JVDataFileSpec HOSE_HS_X_M = new JVDataFileSpec() { Value = nameof(HOSE_HS_X_M), RecordSpec = HS, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HSXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec HOSN_HS_X_M = new JVDataFileSpec() { Value = nameof(HOSN_HS_X_M), RecordSpec = HS, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HSXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec HOYU_HY_X_M = new JVDataFileSpec() { Value = nameof(HOYU_HY_X_M), RecordSpec = HY, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"HYXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec COMM_CS_X_M = new JVDataFileSpec() { Value = nameof(COMM_CS_X_M), RecordSpec = CS, CategorySpec = X, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"CSXM(?<datekey>[0-9]{6}99)(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.MaxValue };
        public static readonly JVDataFileSpec MING_DM_V_M = new JVDataFileSpec() { Value = nameof(MING_DM_V_M), RecordSpec = DM, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"DMVM(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec MING_TM_V_M = new JVDataFileSpec() { Value = nameof(MING_TM_V_M), RecordSpec = TM, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"TMVM(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec WOOD_WC_V_M = new JVDataFileSpec() { Value = nameof(WOOD_WC_V_M), RecordSpec = WC, CategorySpec = V, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"WCVM(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(365) };
        public static readonly JVDataFileSpec WOOD_WC_M_M = new JVDataFileSpec() { Value = nameof(WOOD_WC_M_M), RecordSpec = WC, CategorySpec = M, SaveSpec = JVSaveSpec.M, FileNameRegex = new Regex(@"WCMM(?<datekey>[0-9]{8})(?<datetime>[0-9]{14})\.jvd", RegexOptions.Compiled), ProvidedDuration = TimeSpan.FromDays(0) };

        private JVDataFileSpec()
        {
        }

        public string Value { get; private set; }
        public JVRecordSpec RecordSpec { get; private set; }
        public JVCategorySpec CategorySpec { get; private set; }
        public JVSaveSpec SaveSpec { get; private set; }
        public Regex FileNameRegex { get; private set; }
        public TimeSpan ProvidedDuration { get; private set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as JVDataFileSpec);
        }

        public bool Equals(JVDataFileSpec other)
        {
            return !(other is null) &&
                   Value == other.Value &&
                   EqualityComparer<JVRecordSpec>.Default.Equals(RecordSpec, other.RecordSpec) &&
                   EqualityComparer<JVCategorySpec>.Default.Equals(CategorySpec, other.CategorySpec) &&
                   EqualityComparer<JVSaveSpec>.Default.Equals(SaveSpec, other.SaveSpec) &&
                   EqualityComparer<Regex>.Default.Equals(FileNameRegex, other.FileNameRegex) &&
                   ProvidedDuration.Equals(other.ProvidedDuration);
        }

        public override int GetHashCode()
        {
            int hashCode = -560809519;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Value);
            hashCode = hashCode * -1521134295 + EqualityComparer<JVRecordSpec>.Default.GetHashCode(RecordSpec);
            hashCode = hashCode * -1521134295 + EqualityComparer<JVCategorySpec>.Default.GetHashCode(CategorySpec);
            hashCode = hashCode * -1521134295 + EqualityComparer<JVSaveSpec>.Default.GetHashCode(SaveSpec);
            hashCode = hashCode * -1521134295 + EqualityComparer<Regex>.Default.GetHashCode(FileNameRegex);
            hashCode = hashCode * -1521134295 + ProvidedDuration.GetHashCode();
            return hashCode;
        }

        public static bool operator ==(JVDataFileSpec left, JVDataFileSpec right)
        {
            return EqualityComparer<JVDataFileSpec>.Default.Equals(left, right);
        }

        public static bool operator !=(JVDataFileSpec left, JVDataFileSpec right)
        {
            return !(left == right);
        }

        public override string ToString()
        {
            return $"{Value}, {nameof(RecordSpec)}={RecordSpec}, {nameof(CategorySpec)}={CategorySpec}, {nameof(SaveSpec)}={SaveSpec}, {nameof(FileNameRegex)}={FileNameRegex}, {nameof(ProvidedDuration)}={ProvidedDuration}";
        }
    }
}
